package lostworlds.server.species;

import lostworlds.server.LostWorldsRegistries;
import lostworlds.server.LostWorldsUtils;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class LostWorldsSpeciesTypes {
	public static final DeferredRegister<SpeciesType> SPECIES_TYPES = DeferredRegister.create(LostWorldsRegistries.SPECIES_TYPES, LostWorldsUtils.ID);

	public static final RegistryObject<SpeciesType> ALLOSAURUS_FRAGILIS = SPECIES_TYPES.register("allosaurus_fragilis", () -> new SpeciesType(LostWorldsUtils.rL("geo/allosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/allosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> ANOMALOCARIS_CANADENSIS = SPECIES_TYPES.register("anomalocaris_canadensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/anomalocaris.geo.json"), LostWorldsUtils.rL("textures/model/entity/anomalocaris/texture.png")));
	public static final RegistryObject<SpeciesType> CARNOTAURUS_SASTREI = SPECIES_TYPES.register("carnotaurus_sastrei", () -> new SpeciesType(LostWorldsUtils.rL("geo/carnotaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/carnotaurus/texture.png")));
	public static final RegistryObject<SpeciesType> CHILESAURUS_DIEGOSUAREZI = SPECIES_TYPES.register("chilesaurus_diegosuarezi", () -> new SpeciesType(LostWorldsUtils.rL("geo/chilesaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/chilesaurus/texture.png")));
	public static final RegistryObject<SpeciesType> CRYOLOPHOSAURUS_ELLIOTI_A = SPECIES_TYPES.register("cryolophosaurus_ellioti_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryolophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryolophosaurus/texture_1.png")));
	public static final RegistryObject<SpeciesType> CRYOLOPHOSAURUS_ELLIOTI_B = SPECIES_TYPES.register("cryolophosaurus_ellioti_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryolophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryolophosaurus/texture_2.png")));
	public static final RegistryObject<SpeciesType> CRYPTOCLIDUS_EURYMERUS = SPECIES_TYPES.register("cryptoclidus_eurymerus", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryptoclidus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryptoclidus/texture.png")));
	public static final RegistryObject<SpeciesType> DIICTODON_FELICEPS = SPECIES_TYPES.register("diictodon_feliceps", () -> new SpeciesType(LostWorldsUtils.rL("geo/diictodon.geo.json"), LostWorldsUtils.rL("textures/model/entity/diictodon/texture.png")));
	public static final RegistryObject<SpeciesType> DILOPHOSAURUS_WETHERILLI = SPECIES_TYPES.register("dilophosaurus_wetherilli", () -> new SpeciesType(LostWorldsUtils.rL("geo/dilophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/dilophosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> DIMETRODON_LIMBATUS = SPECIES_TYPES.register("dimetrodon_limbatus", () -> new SpeciesType(LostWorldsUtils.rL("geo/dimetrodon.geo.json"), LostWorldsUtils.rL("textures/model/entity/dimetrodon/texture.png")));
	public static final RegistryObject<SpeciesType> EDAPHOSAURUS_POGONIAS = SPECIES_TYPES.register("edaphosaurus_pogonias", () -> new SpeciesType(LostWorldsUtils.rL("geo/edaphosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/edaphosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> EORAPTOR_LUNENSIS = SPECIES_TYPES.register("eoraptor_lunensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/eoraptor.geo.json"), LostWorldsUtils.rL("textures/model/entity/eoraptor/texture.png")));
	public static final RegistryObject<SpeciesType> EUSTREPTOSPONDYLUS_OXONIENSIS = SPECIES_TYPES.register("eustreptospondylus_oxoniensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/eustreptospondylus.geo.json"), LostWorldsUtils.rL("textures/model/entity/eustreptospondylus/texture.png")));
	public static final RegistryObject<SpeciesType> FUKUIVENATOR_PARADOXUS = SPECIES_TYPES.register("fukuivenator_paradoxus", () -> new SpeciesType(LostWorldsUtils.rL("geo/fukuivenator.geo.json"), LostWorldsUtils.rL("textures/model/entity/fukuivenator/texture.png")));
	public static final RegistryObject<SpeciesType> GIGANOTOSAURUS_CAROLINII = SPECIES_TYPES.register("giganotosaurus_carolinii", () -> new SpeciesType(LostWorldsUtils.rL("geo/giganotosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/giganotosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> GORGONOPS_TORVUS = SPECIES_TYPES.register("gorgonops_torvus", () -> new SpeciesType(LostWorldsUtils.rL("geo/gorgonops.geo.json"), LostWorldsUtils.rL("textures/model/entity/gorgonops/texture.png")));
	public static final RegistryObject<SpeciesType> PINGUINUS_IMPENNIS = SPECIES_TYPES.register("pinguinus_impennis", () -> new SpeciesType(LostWorldsUtils.rL("geo/great_auk.geo.json"), LostWorldsUtils.rL("textures/model/entity/great_auk/texture.png")));
	public static final RegistryObject<SpeciesType> KENTROSAURUS_AETHIOPICUS = SPECIES_TYPES.register("kentrosaurus_aethiopicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/kentrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/kentrosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> LIAONINGOSAURUS_PARADOXUS_A = SPECIES_TYPES.register("liaoningosaurus_paradoxus_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/liaoningosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/liaoningosaurus/texture_1.png")));
	public static final RegistryObject<SpeciesType> LIAONINGOSAURUS_PARADOXUS_B = SPECIES_TYPES.register("liaoningosaurus_paradoxus_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/liaoningosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/liaoningosaurus/texture_2.png")));
	public static final RegistryObject<SpeciesType> NAUTILUS_POMPILIUS = SPECIES_TYPES.register("nautilus_pompilius", () -> new SpeciesType(LostWorldsUtils.rL("geo/nautilus.geo.json"), LostWorldsUtils.rL("textures/model/entity/nautilus/texture.png")));
	public static final RegistryObject<SpeciesType> OPHTHALMOSAURUS_ICENICUS = SPECIES_TYPES.register("ophthalmosaurus_icenicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/ophthalmosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/ophthalmosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> OSTROMIA_CRASSIPES = SPECIES_TYPES.register("ostromia_crassipes", () -> new SpeciesType(LostWorldsUtils.rL("geo/ostromia.geo.json"), LostWorldsUtils.rL("textures/model/entity/ostromia/texture.png")));
	public static final RegistryObject<SpeciesType> OURANOSAURUS_NIGERIENSIS = SPECIES_TYPES.register("ouranosaurus_nigeriensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/ouranosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/ouranosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> PARKSOSAURUS_WARRENI = SPECIES_TYPES.register("parksosaurus_warreni", () -> new SpeciesType(LostWorldsUtils.rL("geo/parksosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/parksosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> PALAEONISCUM_FREIESLEBENI = SPECIES_TYPES.register("palaeoniscum_freieslebeni", () -> new SpeciesType(LostWorldsUtils.rL("geo/palaeoniscum.geo.json"), LostWorldsUtils.rL("textures/model/entity/palaeoniscum/texture.png")));
	public static final RegistryObject<SpeciesType> PROCOMPSOGNATHUS_TRIASSICUS = SPECIES_TYPES.register("procompsognathus_triassicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/procompsognathus.geo.json"), LostWorldsUtils.rL("textures/model/entity/procompsognathus/texture.png")));
	public static final RegistryObject<SpeciesType> PROTOSUCHUS_RICHARDSONI = SPECIES_TYPES.register("protosuchus_richardsoni", () -> new SpeciesType(LostWorldsUtils.rL("geo/protosuchus.geo.json"), LostWorldsUtils.rL("textures/model/entity/protosuchus/texture.png")));
	public static final RegistryObject<SpeciesType> PSITTACOSAURUS_MONGOLIENSIS = SPECIES_TYPES.register("psittacosaurus_mongoliensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/psittacosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/psittacosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> RHINESUCHUS_WHAITSI = SPECIES_TYPES.register("rhinesuchus_whaitsi", () -> new SpeciesType(LostWorldsUtils.rL("geo/rhinesuchus.geo.json"), LostWorldsUtils.rL("textures/model/entity/rhinesuchus/texture.png")));
	public static final RegistryObject<SpeciesType> SUCHOMIMUS_TENERENSIS = SPECIES_TYPES.register("suchomimus_tenerensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/suchomimus.geo.json"), LostWorldsUtils.rL("textures/model/entity/suchomimus/texture.png")));
	public static final RegistryObject<SpeciesType> UTAHRAPTOR_OSTROMMAYSI = SPECIES_TYPES.register("utahraptor_ostrommaysi", () -> new SpeciesType(LostWorldsUtils.rL("geo/utahraptor.geo.json"), LostWorldsUtils.rL("textures/model/entity/utahraptor/texture.png")));
	public static final RegistryObject<SpeciesType> THANOS_SIMONATTOI_A = SPECIES_TYPES.register("thanos_simonattoi_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/thanos.geo.json"), LostWorldsUtils.rL("textures/model/entity/thanos/texture_1.png")));
	public static final RegistryObject<SpeciesType> THANOS_SIMONATTOI_B = SPECIES_TYPES.register("thanos_simonattoi_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/thanos.geo.json"), LostWorldsUtils.rL("textures/model/entity/thanos/texture_2.png")));
	public static final RegistryObject<SpeciesType> TETRACERATOPS_INSIGNIS = SPECIES_TYPES.register("tetraceratops_insignis", () -> new SpeciesType(LostWorldsUtils.rL("geo/tetraceratops.geo.json"), LostWorldsUtils.rL("textures/model/entity/tetraceratops/texture.png")));
	public static final RegistryObject<SpeciesType> TYRANNOSAURUS_REX = SPECIES_TYPES.register("tyrannosaurus_rex", () -> new SpeciesType(LostWorldsUtils.rL("geo/tyrannosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/tyrannosaurus/texture.png")));
	public static final RegistryObject<SpeciesType> ZEPHYROSAURUS_SCHAFFI_A = SPECIES_TYPES.register("zephyrosaurus_schaffi_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/zephyrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/zephyrosaurus/texture_1.png")));
	public static final RegistryObject<SpeciesType> ZEPHYROSAURUS_SCHAFFI_B = SPECIES_TYPES.register("zephyrosaurus_schaffi_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/zephyrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/zephyrosaurus/texture_2.png")));
}
