package lostworlds.server.species;

import lostworlds.server.LostWorldsRegistries;
import lostworlds.server.LostWorldsUtils;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class LostWorldsSpeciesTypes {
	public static final DeferredRegister<SpeciesType> SPECIES_TYPES = DeferredRegister.create(LostWorldsRegistries.SPECIES_TYPES, LostWorldsUtils.ID);

	public static final RegistryObject<SpeciesType> ABSALOMICHTHYS_VELIFER = SPECIES_TYPES.register("absalomichthys_velifer", () -> new SpeciesType(LostWorldsUtils.rL("geo/absalomichthys.geo.json"), LostWorldsUtils.rL("textures/model/entity/absalomichthys/texture.png"), LostWorldsUtils.rL("animations/absalomichthys.animations.json")));
	public static final RegistryObject<SpeciesType> ALLOSAURUS_FRAGILIS = SPECIES_TYPES.register("allosaurus_fragilis", () -> new SpeciesType(LostWorldsUtils.rL("geo/allosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/allosaurus/texture.png"), LostWorldsUtils.rL("animations/allosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> ANOMALOCARIS_CANADENSIS = SPECIES_TYPES.register("anomalocaris_canadensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/anomalocaris.geo.json"), LostWorldsUtils.rL("textures/model/entity/anomalocaris/texture.png"), LostWorldsUtils.rL("animations/anomalocaris.animations.json")));
	public static final RegistryObject<SpeciesType> ANUROGNATHUS_AMMONI = SPECIES_TYPES.register("anurognathus_ammoni", () -> new SpeciesType(LostWorldsUtils.rL("geo/anurognathus.geo.json"), LostWorldsUtils.rL("textures/model/entity/anurognathus/texture.png"), LostWorldsUtils.rL("animations/anurognathus.animations.json")));
	public static final RegistryObject<SpeciesType> CARNOTAURUS_SASTREI = SPECIES_TYPES.register("carnotaurus_sastrei", () -> new SpeciesType(LostWorldsUtils.rL("geo/carnotaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/carnotaurus/texture.png"), LostWorldsUtils.rL("animations/carnotaurus.animations.json")));
	public static final RegistryObject<SpeciesType> CHILESAURUS_DIEGOSUAREZI = SPECIES_TYPES.register("chilesaurus_diegosuarezi", () -> new SpeciesType(LostWorldsUtils.rL("geo/chilesaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/chilesaurus/texture.png"), LostWorldsUtils.rL("animations/chilesaurus.animations.json")));
	public static final RegistryObject<SpeciesType> CRYOLOPHOSAURUS_ELLIOTI_A = SPECIES_TYPES.register("cryolophosaurus_ellioti_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryolophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryolophosaurus/texture_1.png"), LostWorldsUtils.rL("animations/cryolophosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> CRYOLOPHOSAURUS_ELLIOTI_B = SPECIES_TYPES.register("cryolophosaurus_ellioti_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryolophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryolophosaurus/texture_2.png"), LostWorldsUtils.rL("animations/cryolophosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> CRYPTOCLIDUS_EURYMERUS = SPECIES_TYPES.register("cryptoclidus_eurymerus", () -> new SpeciesType(LostWorldsUtils.rL("geo/cryptoclidus.geo.json"), LostWorldsUtils.rL("textures/model/entity/cryptoclidus/texture.png"), LostWorldsUtils.rL("animations/cryptoclidus.animations.json")));
	public static final RegistryObject<SpeciesType> DIICTODON_FELICEPS = SPECIES_TYPES.register("diictodon_feliceps", () -> new SpeciesType(LostWorldsUtils.rL("geo/diictodon.geo.json"), LostWorldsUtils.rL("textures/model/entity/diictodon/texture.png"), LostWorldsUtils.rL("animations/diictodon.animations.json")));
	public static final RegistryObject<SpeciesType> DILOPHOSAURUS_WETHERILLI = SPECIES_TYPES.register("dilophosaurus_wetherilli", () -> new SpeciesType(LostWorldsUtils.rL("geo/dilophosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/dilophosaurus/texture.png"), LostWorldsUtils.rL("animations/dilophosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> DIMETRODON_LIMBATUS = SPECIES_TYPES.register("dimetrodon_limbatus", () -> new SpeciesType(LostWorldsUtils.rL("geo/dimetrodon.geo.json"), LostWorldsUtils.rL("textures/model/entity/dimetrodon/texture.png"), LostWorldsUtils.rL("animations/dimetrodon.animations.json")));
	public static final RegistryObject<SpeciesType> EDAPHOSAURUS_POGONIAS = SPECIES_TYPES.register("edaphosaurus_pogonias", () -> new SpeciesType(LostWorldsUtils.rL("geo/edaphosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/edaphosaurus/texture.png"), LostWorldsUtils.rL("animations/edaphosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> EORAPTOR_LUNENSIS = SPECIES_TYPES.register("eoraptor_lunensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/eoraptor.geo.json"), LostWorldsUtils.rL("textures/model/entity/eoraptor/texture.png"), LostWorldsUtils.rL("animations/eoraptor.animations.json")));
	public static final RegistryObject<SpeciesType> EUSTREPTOSPONDYLUS_OXONIENSIS = SPECIES_TYPES.register("eustreptospondylus_oxoniensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/eustreptospondylus.geo.json"), LostWorldsUtils.rL("textures/model/entity/eustreptospondylus/texture.png"), LostWorldsUtils.rL("animations/eustreptospondylus.animations.json")));
	public static final RegistryObject<SpeciesType> FUKUIVENATOR_PARADOXUS = SPECIES_TYPES.register("fukuivenator_paradoxus", () -> new SpeciesType(LostWorldsUtils.rL("geo/fukuivenator.geo.json"), LostWorldsUtils.rL("textures/model/entity/fukuivenator/texture.png"), LostWorldsUtils.rL("animations/fukuivenator.animations.json")));
	public static final RegistryObject<SpeciesType> GIGANOTOSAURUS_CAROLINII = SPECIES_TYPES.register("giganotosaurus_carolinii", () -> new SpeciesType(LostWorldsUtils.rL("geo/giganotosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/giganotosaurus/texture.png"), LostWorldsUtils.rL("animations/giganotosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> GORGONOPS_TORVUS = SPECIES_TYPES.register("gorgonops_torvus", () -> new SpeciesType(LostWorldsUtils.rL("geo/gorgonops.geo.json"), LostWorldsUtils.rL("textures/model/entity/gorgonops/texture.png"), LostWorldsUtils.rL("animations/gorgonops.animations.json")));
	public static final RegistryObject<SpeciesType> PINGUINUS_IMPENNIS = SPECIES_TYPES.register("pinguinus_impennis", () -> new SpeciesType(LostWorldsUtils.rL("geo/great_auk.geo.json"), LostWorldsUtils.rL("textures/model/entity/great_auk/texture.png"), LostWorldsUtils.rL("animations/great_auk.animations.json")));
	public static final RegistryObject<SpeciesType> KENTROSAURUS_AETHIOPICUS = SPECIES_TYPES.register("kentrosaurus_aethiopicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/kentrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/kentrosaurus/texture.png"), LostWorldsUtils.rL("animations/kentrosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> LIAONINGOSAURUS_PARADOXUS_A = SPECIES_TYPES.register("liaoningosaurus_paradoxus_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/liaoningosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/liaoningosaurus/texture_1.png"), LostWorldsUtils.rL("animations/liaoningosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> LIAONINGOSAURUS_PARADOXUS_B = SPECIES_TYPES.register("liaoningosaurus_paradoxus_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/liaoningosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/liaoningosaurus/texture_2.png"), LostWorldsUtils.rL("animations/liaoningosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> MESOSAURUS_TENUIDENS = SPECIES_TYPES.register("mesosaurus_tenuidens", () -> new SpeciesType(LostWorldsUtils.rL("geo/mesosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/mesosaurus/texture.png"), LostWorldsUtils.rL("animations/mesosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> NAUTILUS_POMPILIUS = SPECIES_TYPES.register("nautilus_pompilius", () -> new SpeciesType(LostWorldsUtils.rL("geo/nautilus.geo.json"), LostWorldsUtils.rL("textures/model/entity/nautilus/texture.png"), LostWorldsUtils.rL("animations/nautilus.animations.json")));
	public static final RegistryObject<SpeciesType> OPHTHALMOSAURUS_ICENICUS = SPECIES_TYPES.register("ophthalmosaurus_icenicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/ophthalmosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/ophthalmosaurus/texture.png"), LostWorldsUtils.rL("animations/ophthalmosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> OSTROMIA_CRASSIPES = SPECIES_TYPES.register("ostromia_crassipes", () -> new SpeciesType(LostWorldsUtils.rL("geo/ostromia.geo.json"), LostWorldsUtils.rL("textures/model/entity/ostromia/texture.png"), LostWorldsUtils.rL("animations/ostromia.animations.json")));
	public static final RegistryObject<SpeciesType> OURANOSAURUS_NIGERIENSIS = SPECIES_TYPES.register("ouranosaurus_nigeriensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/ouranosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/ouranosaurus/texture.png"), LostWorldsUtils.rL("animations/ouranosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> PARKSOSAURUS_WARRENI = SPECIES_TYPES.register("parksosaurus_warreni", () -> new SpeciesType(LostWorldsUtils.rL("geo/parksosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/parksosaurus/texture.png"), LostWorldsUtils.rL("animations/parksosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> PALAEONISCUM_FREIESLEBENI = SPECIES_TYPES.register("palaeoniscum_freieslebeni", () -> new SpeciesType(LostWorldsUtils.rL("geo/palaeoniscum.geo.json"), LostWorldsUtils.rL("textures/model/entity/palaeoniscum/texture.png"), LostWorldsUtils.rL("animations/palaeoniscum.animations.json")));
	public static final RegistryObject<SpeciesType> PROCOMPSOGNATHUS_TRIASSICUS = SPECIES_TYPES.register("procompsognathus_triassicus", () -> new SpeciesType(LostWorldsUtils.rL("geo/procompsognathus.geo.json"), LostWorldsUtils.rL("textures/model/entity/procompsognathus/texture.png"), LostWorldsUtils.rL("animations/procompsognathus.animations.json")));
	public static final RegistryObject<SpeciesType> PROTOSUCHUS_RICHARDSONI = SPECIES_TYPES.register("protosuchus_richardsoni", () -> new SpeciesType(LostWorldsUtils.rL("geo/protosuchus.geo.json"), LostWorldsUtils.rL("textures/model/entity/protosuchus/texture.png"), LostWorldsUtils.rL("animations/protosuchus.animations.json")));
	public static final RegistryObject<SpeciesType> PSITTACOSAURUS_MONGOLIENSIS = SPECIES_TYPES.register("psittacosaurus_mongoliensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/psittacosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/psittacosaurus/texture.png"), LostWorldsUtils.rL("animations/psittacosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> RHINESUCHUS_WHAITSI = SPECIES_TYPES.register("rhinesuchus_whaitsi", () -> new SpeciesType(LostWorldsUtils.rL("geo/rhinesuchus.geo.json"), LostWorldsUtils.rL("textures/model/entity/rhinesuchus/texture.png"), LostWorldsUtils.rL("animations/rhinesuchus.animations.json")));
	public static final RegistryObject<SpeciesType> SUCHOMIMUS_TENERENSIS = SPECIES_TYPES.register("suchomimus_tenerensis", () -> new SpeciesType(LostWorldsUtils.rL("geo/suchomimus.geo.json"), LostWorldsUtils.rL("textures/model/entity/suchomimus/texture.png"), LostWorldsUtils.rL("animations/suchomimus.animations.json")));
	public static final RegistryObject<SpeciesType> UTAHRAPTOR_OSTROMMAYSI = SPECIES_TYPES.register("utahraptor_ostrommaysi", () -> new SpeciesType(LostWorldsUtils.rL("geo/utahraptor.geo.json"), LostWorldsUtils.rL("textures/model/entity/utahraptor/texture.png"), LostWorldsUtils.rL("animations/utahraptor.animations.json")));
	public static final RegistryObject<SpeciesType> THANOS_SIMONATTOI_A = SPECIES_TYPES.register("thanos_simonattoi_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/thanos.geo.json"), LostWorldsUtils.rL("textures/model/entity/thanos/texture_1.png"), LostWorldsUtils.rL("animations/thanos.animations.json")));
	public static final RegistryObject<SpeciesType> THANOS_SIMONATTOI_B = SPECIES_TYPES.register("thanos_simonattoi_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/thanos.geo.json"), LostWorldsUtils.rL("textures/model/entity/thanos/texture_2.png"), LostWorldsUtils.rL("animations/thanos.animations.json")));
	public static final RegistryObject<SpeciesType> TETRACERATOPS_INSIGNIS = SPECIES_TYPES.register("tetraceratops_insignis", () -> new SpeciesType(LostWorldsUtils.rL("geo/tetraceratops.geo.json"), LostWorldsUtils.rL("textures/model/entity/tetraceratops/texture.png"), LostWorldsUtils.rL("animations/tetraceratops.animations.json")));
	public static final RegistryObject<SpeciesType> TOYOTAMAPHIMEIA_MACHIKANENSIS_A = SPECIES_TYPES.register("toyotamaphimeia_machikanensis_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/toyotamaphimeia.geo.json"), LostWorldsUtils.rL("textures/model/entity/toyotamaphimeia/texture_1.png"), LostWorldsUtils.rL("animations/toyotamaphimeia.animations.json")));
	public static final RegistryObject<SpeciesType> TOYOTAMAPHIMEIA_MACHIKANENSIS_B = SPECIES_TYPES.register("toyotamaphimeia_machikanensis_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/toyotamaphimeia.geo.json"), LostWorldsUtils.rL("textures/model/entity/toyotamaphimeia/texture_2.png"), LostWorldsUtils.rL("animations/toyotamaphimeia.animations.json")));
	public static final RegistryObject<SpeciesType> TYRANNOSAURUS_REX = SPECIES_TYPES.register("tyrannosaurus_rex", () -> new SpeciesType(LostWorldsUtils.rL("geo/tyrannosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/tyrannosaurus/texture.png"), LostWorldsUtils.rL("animations/tyrannosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> ZEPHYROSAURUS_SCHAFFI_A = SPECIES_TYPES.register("zephyrosaurus_schaffi_a", () -> new SpeciesType(LostWorldsUtils.rL("geo/zephyrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/zephyrosaurus/texture_1.png"), LostWorldsUtils.rL("animations/zephyrosaurus.animations.json")));
	public static final RegistryObject<SpeciesType> ZEPHYROSAURUS_SCHAFFI_B = SPECIES_TYPES.register("zephyrosaurus_schaffi_b", () -> new SpeciesType(LostWorldsUtils.rL("geo/zephyrosaurus.geo.json"), LostWorldsUtils.rL("textures/model/entity/zephyrosaurus/texture_2.png"), LostWorldsUtils.rL("animations/zephyrosaurus.animations.json")));
}
